version: 0.0
os: linux

files:
  - source: website/
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/antes.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/depois.sh
      timeout: 300
      runas: root