# Versão do buildspec (padrão do CodeBuild)
version: 0.2

# Fases do processo de build
phases:

  install:
    commands:
      - echo "========== INICIO DO BUILD =========="  # Marca o início do processo no log
      - echo "Preparando ambiente..."               # Mensagem informativa (não executa ação)

  build:
    commands:
      - echo "========== INICIO UPLOAD =========="  # Início da etapa de upload para o S3

      - echo "Subindo VPC..."                      # Log antes de enviar o template da VPC
      - aws s3 cp network/vpc.yaml s3://iac-cloudformation-templates-bucket/network/vpc.yaml  # Upload do template de VPC para o S3

      - echo "Subindo Security..."                 # Log antes de enviar o template de segurança
      - aws s3 cp security/security.yaml s3://iac-cloudformation-templates-bucket/security/security.yaml  # Upload do template de segurança (Security Group)

      - echo "========== FINALIZADO =========="    # Indica que o processo terminou com sucesso

# Define quais arquivos serão gerados como artefato do build
artifacts:
  files:
    - '**/*'   # Inclui TODOS os arquivos do projeto como artefato