AWSTemplateFormatVersion: '2010-09-09'
Description: Stack2 EC2 usando recursos de rede importados da stack1.

Parameters:
  KeyName:
    Description: Nome da KeyPair existente
    Type: AWS::EC2::KeyPair::KeyName
    Default: LinuxUbuntu

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro

      KeyName: !Ref KeyName

      ImageId: ami-0030e4319cbf4dbf2

      SubnetId: !ImportValue stack1-public-subnet-1-id

      SecurityGroupIds:
        - !ImportValue stack1-security-group-id

      Tags:
        - Key: Name
          Value: stack2-ec2

Outputs:

  InstanceId:
    Description: ID da instância EC2
    Value: !Ref EC2Instance

  InstancePublicIp:
    Description: IP público da instância
    Value: !GetAtt EC2Instance.PublicIp

  ImportedVpcId:
    Description: VPC importada da stack1
    Value: !ImportValue stack1-vpc-id