AWSTemplateFormatVersion: '2010-09-09'
Description: Stack2 EC2 usando recursos de rede importados de stack1.

Mappings:
  # KeyPair está fixo como LinuxUbuntu, pois já existe na região de deploy.
  Region2AMI:
    us-east-1:
      AMI: ami-0a313d6098716f372
    us-east-2:
      AMI: ami-0db9040eb3ab74509
    us-west-1:
      AMI: ami-04b9e92b5572fa0d1
    us-west-2:
      AMI: ami-0d6621c01e8c2de2c
    eu-west-1:
      AMI: ami-047bb4163c506cd98
    eu-central-1:
      AMI: ami-0ac80df6eff0e70b5

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: !Ref KeyName
      ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', AMI]
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !ImportValue stack1-public-subnet-1-id
          GroupSet:
            - !ImportValue stack1-security-group-id
          AssociatePublicIpAddress: true
      Tags:
        - Key: Name
          Value: stack2-ec2

Outputs:
  InstanceId:
    Description: ID da instância EC2
    Value: !Ref EC2Instance

  InstancePublicIp:
    Description: IP público da instância
    Value: !GetAtt [EC2Instance, PublicIp]

  VpcIdImported:
    Description: VPC importada da stack1
    Value: !ImportValue stack1-vpc-id
