AWSTemplateFormatVersion: '2010-09-09'
Description: Stack2 EC2 usando recursos de rede importados da stack1.

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: LinuxUbuntu

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro

      ImageId: ami-0030e4319cbf4dbf2

      KeyName: !Ref KeyName

      SubnetId: !ImportValue stack1-public-subnet-1-id

      SecurityGroupIds:
        - !ImportValue stack1-security-group-id

      Tags:
        - Key: Name
          Value: stack2-ec2

Outputs:

  InstanceId:
    Value: !Ref EC2Instance

  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp