AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 stack

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: LinuxUbuntu

  SecurityStackName:
    Type: String
    Default: security-stack

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro

      ImageId: ami-0030e4319cbf4dbf2

      KeyName: !Ref KeyName

      SubnetId: !ImportValue network-public-subnet1

      SecurityGroupIds:
        - Fn::ImportValue:
            Fn::Sub: "${SecurityStackName}-ec2-sg"

      UserData:
        Fn::Base64: |
          #!/bin/bash
          set -e
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
          apt-get install -y apache2
          systemctl enable apache2
          systemctl start apache2

      Tags:
        - Key: Name
          Value: ec2-instance

Outputs:

  InstanceId:
    Value: !Ref EC2Instance

  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
