AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 stack

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: LinuxUbuntu

  VpcStackName:
    Type: String
    Default: vpc-stack

  SecurityStackName:
    Type: String
    Default: security-stack

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro

      ImageId: ami-0030e4319cbf4dbf2

      KeyName: !Ref KeyName

      SubnetId: !ImportValue
        Fn::Sub: ${VpcStackName}-public-subnet1

      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: ${SecurityStackName}-ec2-sg

      UserData: !Base64 |
        #!/bin/bash
        set -e

        # Atualiza pacotes
        apt update -y

        # Instala Apache
        apt install -y apache2

        # Inicia Apache
        systemctl start apache2
        systemctl enable apache2

          Tags:
            - Key: Name
              Value: ec2-instance

Outputs:

  InstanceId:
    Value: !Ref EC2Instance

  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp